<?php
use App\Http\Controllers\{AuthController,CategoryController,DashboardController,ProductController,ReportController,SettingsController,StockController,SupplierController,UserController};
use Illuminate\Support\Facades\Route;
Route::redirect('/', '/dashboard');
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'create'])->name('login');Route::post('/login',[AuthController::class,'store'])->name('login.store');});
Route::middleware('auth')->group(function(){Route::post('/logout',[AuthController::class,'destroy'])->name('logout');Route::get('/dashboard',DashboardController::class)->name('dashboard');Route::get('/products',[ProductController::class,'index'])->name('products.index');Route::get('/products/export',[ProductController::class,'export'])->name('products.export');
Route::get('/products/import',[ProductController::class,'importForm'])->name('products.import.form');
Route::post('/products/import',[ProductController::class,'import'])->name('products.import');
Route::middleware('role:admin,manajer_gudang')->group(function(){Route::get('/products/create',[ProductController::class,'create'])->name('products.create');});Route::get('/products/{id}',[ProductController::class,'show'])->name('products.show');Route::middleware('role:admin,manajer_gudang')->group(function(){Route::post('/products',[ProductController::class,'store'])->name('products.store');Route::get('/products/{id}/edit',[ProductController::class,'edit'])->name('products.edit');Route::put('/products/{id}',[ProductController::class,'update'])->name('products.update');Route::delete('/products/{id}',[ProductController::class,'destroy'])->name('products.destroy');Route::get('/reports',[ReportController::class,'index'])->name('reports.index');});Route::middleware('role:admin,manajer_gudang,staff_gudang')->group(function(){Route::get('/stock',[StockController::class,'history'])->name('stock.history');Route::get('/stock/in',[StockController::class,'createIn'])->name('stock.in.create');Route::post('/stock/in',[StockController::class,'storeIn'])->name('stock.in.store');Route::get('/stock/out',[StockController::class,'createOut'])->name('stock.out.create');Route::post('/stock/out',[StockController::class,'storeOut'])->name('stock.out.store');Route::get('/stock/opname',[StockController::class,'createOpname'])->name('stock.opname.create');Route::post('/stock/opname',[StockController::class,'storeOpname'])->name('stock.opname.store');Route::post('/stock/in/{id}/confirm',[StockController::class,'confirmIn'])->name('stock.in.confirm');Route::post('/stock/out/{id}/confirm',[StockController::class,'confirmOut'])->name('stock.out.confirm');});Route::middleware('role:admin')->group(function(){Route::resource('categories',CategoryController::class)->only(['index','store','update','destroy']);Route::resource('suppliers',SupplierController::class)->only(['index','store','edit','update','destroy']);Route::get('/users',[UserController::class,'index'])->name('users.index');Route::post('/users',[UserController::class,'store'])->name('users.store');Route::get('/users/create',[UserController::class,'create'])->name('users.create');Route::get('/users/{user}',[UserController::class,'show'])->name('users.show');Route::get('/users/{user}/edit',[UserController::class,'edit'])->name('users.edit');Route::put('/users/{user}',[UserController::class,'update'])->name('users.update');Route::delete('/users/{user}',[UserController::class,'destroy'])->name('users.destroy');
Route::get('/settings',[SettingsController::class,'index'])->name('settings.index');
Route::put('/settings',[SettingsController::class,'update'])->name('settings.update');

Route::get('/products/export',[ProductController::class,'export'])->name('products.export');Route::get('/products/import',[ProductController::class,'importForm'])->name('products.import.form');Route::post('/products/import',[ProductController::class,'import'])->name('products.import');
});});


